import {
  FaCode,
  FaProjectDiagram,
  FaCheckDouble,
  FaTable,
  FaTerminal,
  FaChartLine,
} from "react-icons/fa";

export const FEATURES = [
  {
    id: "lexical",
    title: "Lexical Analysis",
    icon: FaCode,
    color: "from-blue-500 to-cyan-500",
    points: ["Token visualization", "Keyword & operator recognition"],
    href: "visualizer.html",
    cta: "Explore Visualizer",
  },
  {
    id: "syntax",
    title: "Syntax Analysis",
    icon: FaProjectDiagram,
    color: "from-violet-500 to-purple-500",
    points: ["Parse tree generation", "Grammar validation"],
    href: "visualizer.html",
    cta: "Explore Visualizer",
  },
  {
    id: "semantic",
    title: "Semantic Analysis",
    icon: FaCheckDouble,
    color: "from-orange-500 to-amber-500",
    points: ["Type checking", "Symbol table visualization"],
    href: "visualizer.html",
    cta: "Explore Visualizer",
  },
  {
    id: "icg",
    title: "Intermediate Code Generation",
    icon: FaTable,
    color: "from-emerald-500 to-teal-500",
    points: ["Three-address code generation", "IR visualization"],
    href: "visualizer.html",
    cta: "Explore Visualizer",
  },
  {
    id: "editor",
    title: "Online Code Editor",
    icon: FaTerminal,
    color: "from-green-500 to-emerald-500",
    points: ["Multi-language support", "Code execution", "Output console"],
    href: "editor.html",
    cta: "Open Editor",
  },
  {
    id: "complexity",
    title: "Time Complexity Analyzer",
    icon: FaChartLine,
    color: "from-pink-500 to-rose-500",
    points: ["Complexity estimation", "Runtime & memory analysis", "Performance graphs"],
    href: "editor.html",
    cta: "Try Analysis",
  },
];
